### ISSUE TITLE
Installation steps are not in the right order.

### ISSUE THREAD

**Issue by FredBezies** [specialworld83/repository_eos#1]
Hello.

Looking at your readme, I noticed installation steps are upside down.

1) You add a the key
2) You ask for a package from a repository not included in /etc/pacman.conf
3) You give informations on how to add this repository

So right order for have to be:

```
sudo pacman-key --recv-keys AEE1E900
sudo nano /etc/pacman.conf
sudo pacman -S codelinsoft-keyring
```

**Comment by specialworld83** [comment]
Problem solved
