### ISSUE TITLE
Error while trying to install package from your repository: unknown trust key.

### ISSUE THREAD

**Issue by FredBezies** [specialworld83/repository_eos#2]
This is a followup of bug #1 ; every single time I try to install eos-settings-manager, pacman says that the package could be corrupted because signing key is unknown trust.

I had to sign it locally to install eos-settings-manager :(

I followed this page: https://wiki.archlinux.org/index.php/Pacman/Package_signing#Adding_unofficial_keys

**Comment by specialworld83** [comment]
Problem solved
